name: aws-workspaces
icon: snap/gui/aws-workspaces.svg
summary: Amazon Workspaces
base: core20
description: |
  Client for Amazon WorkSpaces - a managed, secure Desktop-as-a-Service (DaaS) solution.
  NOTE: This wrapper is not verified by, affiliated with, or supported by Amazon.com, Inc. This snap will be de-listed if/when Amazon decide to distribute
  an official Workspaces client snap.
adopt-info: workspaces
confinement: strict
grade: stable
architectures:
  - build-on: amd64
    run-on: amd64
compression: lzo

apps:
  aws-workspaces:
    command: usr/bin/workspacesclient
    environment:
      NO_AT_BRIDGE: 1

    extensions:
      - gnome-3-38
    plugs:
      - audio-playback
      - audio-record
      - bluez
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - mount-observe
      - network
      - network-status
      - network-observe
      - opengl
      - process-control
      - screen-inhibit-control
      - wayland
      - x11
      - shmem
#      - dbus-workspaces

#slots:
#  dbus-workspaces:
#    interface: dbus
#    bus: session
#    name: com.amazon.workspacesclient

plugs:
  shmem:
    interface: shared-memory
    private: true

parts:
  workspaces:
    plugin: dump
    source: https://d3nt0h4h6pmmc4.cloudfront.net/new_workspacesclient_focal_amd64.deb
    source-type: deb
    override-build: |
      snapcraftctl build
      snapcraftctl set-version 4.7.0.4312
    stage-packages:
      - libgraphicsmagick++-q16-12
      - liblttng-ust0
      - libusb-1.0-0
      - libva2
      - libxcb-util1
      - desktop-file-utils
      - libhiredis0.14
      - libsoup2.4-1
      - libva-drm2
      - libva-x11-2
      - libvdpau1
      - libwebkit2gtk-4.0-37
      - libglib2.0-bin
      - libgtk-3-0
      - libxcb-res0
      - libgtk2.0-bin

  lsb-release-mock:
    plugin: dump
    source: snap/local/script
    source-type: local
    organize:
      '*': /usr/bin/

